cabal-version: 3.0
name: godot-haskell-gdextension
version: 4.1.0.0
synopsis: Haskell bindings for the Godot game engine API
description: This package contains Haskell bindings for GDExtension and the Godot API. For details and examples, see README.md
license: Apache-2.0
license-file: LICENSE
build-type: Custom

custom-setup
  setup-depends:
    Cabal,
    base,
    directory,

common warnings
  ghc-options: -Wall

library
  import: warnings
  hs-source-dirs: lib
  exposed-modules: GodotApi
  build-depends: base
  build-tool-depends: c2hs:c2hs
  default-language: GHC2021
